kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $.Chart.Name }}
  labels:
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Chart.Name }}-{{ .Values.DOCKER_IMAGE_TAG }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.REPLICAS }}
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  revisionHistoryLimit: {{ .Values.REVISION_HISTORY_LIMIT }}
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}
        version: "{{ $.Chart.Name }}-{{ .Values.DOCKER_IMAGE_TAG }}"
    spec:
      restartPolicy: Always
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ .Values.CONTAINER_REGISTRY }}/{{ .Values.DOCKER_IMAGE_NAME }}:{{ .Values.DOCKER_IMAGE_TAG }}"
          imagePullPolicy: {{ .Values.DOCKER_IMAGE_PULL_POLICY }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 150m
              memory: 512Mi
            requests:
              cpu: 5m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /api/v1/heathcheck
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 3
          env:
            - name: DATABASE_HOSTNAME
              value: os2iot-postgres-svc
            - name: DATABASE_PORT
              value: '5432'
            - name: KAFKA_HOSTNAME
              value: os2iot-kafka-svc
            - name: KAFKA_PORT
              value: '9092'
            - name: CHIRPSTACK_APPLICATION_SERVER_HOSTNAME
              value: chirpstack-application-server-svc
            - name: CHIRPSTACK_NETWORK_SERVER
              value: chirpstack-network-server-svc
            - name: CS_MQTT_HOSTNAME
              value: mosquitto-svc
            - name: CS_MQTT_PORT
              value: '1883'
            - name: BACKEND_BASEURL
              value: 'https://test-os2iot-backend.os2iot.dk'
            - name: KOMBIT_CERTIFICATEPRIVATEKEY
              value: "{{ .Values.KOMBIT_CERTIFICATEPRIVATEKEY }}"
            - name: KOMBIT_ENTRYPOINT
              value: "{{ .Values.KOMBIT_ENTRYPOINT }}"
